export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_AIRPORTS_SUCCESS = 'GET_AIRPORTS_SUCCESS'
export const AIRPORTS_IS_LOADING = 'AIRPORTS_IS_LOADING'

export const GET_FLIGHTS_SUCCESS = 'GET_FLIGHTS_SUCCESS'

export const POST_BOOKING_PENDING = 'POST_BOOKING_PENDING'
export const POST_BOOKING_SUCCESS = 'POST_BOOKING_SUCCESS'