export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_GUEST_ID = 'SET_GUEST_ID';
export const GET_AIRPORTS_SUCCESS = 'GET_AIRPORTS_SUCCESS'
export const GET_AIRPORTS_PENDING = 'GET_AIRPORTS_PENDING'

export const GET_FLIGHTS_SUCCESS = 'GET_FLIGHTS_SUCCESS'
export const GET_FLIGHTS_PENDING = 'GET_FLIGHTS_PENDING'

export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS'
export const GET_TICKETS_PENDING = 'GET_TICKETS_PENDING'

export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS'
export const GET_BOOKING_PENDING = 'GET_BOOKING_PENDING'

export const POST_BOOKING_SUCCESS = 'POST_BOOKING_SUCCESS'
export const POST_BOOKING_PENDING = 'POST_BOOKING_PENDING'